server:
  port: 8769


spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: localhost2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost1:8768/eureka/