server:
  port: 8768

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/